In [ ]:
import torch

import torch.nn as nn

In [1]:
# artificial data
import sklearn
from sklearn import datasets
import pandas as pd

# from sklearn we are going to select one dataset
data=datasets.make_regression()
df = pd.DataFrame(data[0], columns=[f"feature_{i+1}" for i in range(data[0].shape[1])])
df["target"] = data[1]

In [4]:
df.shape

(100, 101)

In [39]:
# Layers
c0 = nn.Conv1d(1, 128, 1)
maxpool = nn.MaxPool1d(2)
avgpool = nn.AvgPool1d(2)

# Input
x = torch.rand(100, 20, 1)
x = x.transpose(1, 2)
print(x.shape)

# Conv
x = c0(x)
print(x.shape)

torch.Size([100, 1, 20])
torch.Size([100, 128, 20])


In [33]:
x = avgpool(x)
x.shape

torch.Size([100, 128, 10])

In [35]:
x = maxpool(x)
x.shape

torch.Size([100, 128, 10])

#### 

In [38]:
y = torch.cat((x, x, x), 2)
y.shape


torch.Size([100, 128, 30])

In [40]:
(x1, _) = torch.max(x, dim=2)
x2 = torch.mean(x, dim=2)
x = x1 + x2
x1.shape, x2.shape, x.shape

(torch.Size([100, 128]), torch.Size([100, 128]), torch.Size([100, 128]))

In [42]:
x = torch.rand(2, 3, 4)
x

tensor([[[0.0450, 0.1499, 0.8271, 0.9488],
         [0.6914, 0.2709, 0.5344, 0.7879],
         [0.0418, 0.5794, 0.7829, 0.4619]],

        [[0.8227, 0.8590, 0.5337, 0.1601],
         [0.4036, 0.8694, 0.6340, 0.4299],
         [0.3455, 0.0540, 0.2463, 0.4883]]])

In [43]:
torch.mean(x, dim=2)

tensor([[0.4927, 0.5711, 0.4665],
        [0.5939, 0.5842, 0.2835]])

In [44]:
maxpool(x)

tensor([[[0.1499, 0.9488],
         [0.6914, 0.7879],
         [0.5794, 0.7829]],

        [[0.8590, 0.5337],
         [0.8694, 0.6340],
         [0.3455, 0.4883]]])

In [45]:
avgpool(x)

tensor([[[0.0975, 0.8880],
         [0.4811, 0.6611],
         [0.3106, 0.6224]],

        [[0.8409, 0.3469],
         [0.6365, 0.5319],
         [0.1998, 0.3673]]])